// <auto-generated />
using System;
using FamilyTreeAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FamilyTreeAPI.Migrations
{
    [DbContext(typeof(FamilyTreeContext))]
    [Migration("20260421194357_ProductionSync")]
    partial class ProductionSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FamilyTreeAPI.Models.Album", b =>
                {
                    b.Property<int>("AlbumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("AlbumID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlbumID"));

                    b.Property<string>("CoverPhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("CoverPhotoUrl");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<int?>("EventID")
                        .HasColumnType("integer")
                        .HasColumnName("EventID");

                    b.Property<int>("FamilyID")
                        .HasColumnType("integer")
                        .HasColumnName("FamilyID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Visibility");

                    b.HasKey("AlbumID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EventID");

                    b.HasIndex("FamilyID");

                    b.ToTable("Album");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.AlbumComment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CommentID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommentID"));

                    b.Property<int>("AlbumID")
                        .HasColumnType("integer")
                        .HasColumnName("AlbumID");

                    b.Property<int>("AuthorID")
                        .HasColumnType("integer")
                        .HasColumnName("AuthorID");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("CommentID");

                    b.HasIndex("AlbumID");

                    b.HasIndex("AuthorID");

                    b.ToTable("AlbumComment");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.AlbumPermission", b =>
                {
                    b.Property<int>("PermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PermissionID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermissionID"));

                    b.Property<int>("AlbumID")
                        .HasColumnType("integer")
                        .HasColumnName("AlbumID");

                    b.Property<bool>("CanAddPhotos")
                        .HasColumnType("boolean")
                        .HasColumnName("CanAddPhotos");

                    b.Property<bool>("CanComment")
                        .HasColumnType("boolean")
                        .HasColumnName("CanComment");

                    b.Property<bool>("CanView")
                        .HasColumnType("boolean")
                        .HasColumnName("CanView");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<int?>("PersonID")
                        .HasColumnType("integer")
                        .HasColumnName("PersonID");

                    b.Property<int?>("UserID")
                        .HasColumnType("integer")
                        .HasColumnName("UserID");

                    b.HasKey("PermissionID");

                    b.HasIndex("AlbumID");

                    b.HasIndex("PersonID");

                    b.HasIndex("UserID");

                    b.ToTable("AlbumPermission");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.City", b =>
                {
                    b.Property<int>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CityID"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CityID");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            CityID = 1,
                            CountryName = "France",
                            Name = "Paris"
                        },
                        new
                        {
                            CityID = 2,
                            CountryName = "France",
                            Name = "Lyon"
                        },
                        new
                        {
                            CityID = 3,
                            CountryName = "France",
                            Name = "Marseille"
                        },
                        new
                        {
                            CityID = 4,
                            CountryName = "Cameroun",
                            Name = "Yaoundé"
                        },
                        new
                        {
                            CityID = 5,
                            CountryName = "Cameroun",
                            Name = "Douala"
                        });
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.Connexion", b =>
                {
                    b.Property<int>("ConnexionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConnexionID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EmailVerificationCode")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime?>("EmailVerificationExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EmailVerificationSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<int?>("FamilyID")
                        .HasColumnType("integer");

                    b.Property<int?>("IDPerson")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordResetCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("PasswordResetExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ProfileCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ConnexionID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FamilyID");

                    b.HasIndex("IDPerson")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Connexion");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.Event", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("FamilyID")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("EventID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FamilyID");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.EventParticipant", b =>
                {
                    b.Property<int>("EventParticipantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventParticipantID"));

                    b.Property<int>("EventID")
                        .HasColumnType("integer");

                    b.Property<int>("PersonID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("EventParticipantID");

                    b.HasIndex("EventID");

                    b.HasIndex("PersonID");

                    b.ToTable("EventParticipant");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.EventPhoto", b =>
                {
                    b.Property<int>("EventPhotoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventPhotoID"));

                    b.Property<string>("Caption")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("EventID")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UploadedBy")
                        .HasColumnType("integer");

                    b.HasKey("EventPhotoID");

                    b.HasIndex("EventID");

                    b.HasIndex("UploadedBy");

                    b.ToTable("EventPhoto");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.Family", b =>
                {
                    b.Property<int>("FamilyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FamilyID"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InviteCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("FamilyID");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Family");

                    b.HasData(
                        new
                        {
                            FamilyID = 1,
                            CreatedDate = new DateTime(2026, 4, 21, 19, 43, 57, 20, DateTimeKind.Utc).AddTicks(3470),
                            Description = "Famille de démonstration",
                            FamilyName = "Famille Exemple"
                        });
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.FamilyRelation", b =>
                {
                    b.Property<int>("RelationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("RelationID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RelationID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("EndDate");

                    b.Property<int>("FamilyID")
                        .HasColumnType("integer")
                        .HasColumnName("FamilyID");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("Notes");

                    b.Property<int>("PersonID")
                        .HasColumnType("integer")
                        .HasColumnName("PersonID");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("RelationType");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("StartDate");

                    b.HasKey("RelationID");

                    b.HasIndex("FamilyID");

                    b.HasIndex("PersonID");

                    b.ToTable("FamilyRelation");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.MarriageUnion", b =>
                {
                    b.Property<int>("UnionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("UnionID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UnionID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("Location");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("Notes");

                    b.Property<DateTime>("UnionDate")
                        .HasColumnType("date")
                        .HasColumnName("UnionDate");

                    b.Property<string>("UnionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("UnionType");

                    b.Property<bool>("Validated")
                        .HasColumnType("boolean")
                        .HasColumnName("Validated");

                    b.Property<int>("WeddingID")
                        .HasColumnType("integer")
                        .HasColumnName("WeddingID");

                    b.HasKey("UnionID");

                    b.HasIndex("WeddingID");

                    b.ToTable("MarriageUnion");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonID"));

                    b.Property<string>("Activity")
                        .HasMaxLength(2147483647)
                        .HasColumnType("text");

                    b.Property<bool>("Alive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CanLogin")
                        .HasColumnType("boolean");

                    b.Property<int>("CityID")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeathDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(2147483647)
                        .HasColumnType("text");

                    b.Property<int?>("FamilyID")
                        .HasColumnType("integer");

                    b.Property<int?>("FatherID")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("text");

                    b.Property<int?>("MaternalFamilyID")
                        .HasColumnType("integer")
                        .HasColumnName("MaternalFamilyID");

                    b.Property<int?>("MotherID")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(2147483647)
                        .HasColumnType("text");

                    b.Property<bool>("ParentLinkConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("PaternalFamilyID")
                        .HasColumnType("integer")
                        .HasColumnName("PaternalFamilyID");

                    b.Property<string>("PendingFatherName")
                        .HasMaxLength(2147483647)
                        .HasColumnType("text");

                    b.Property<string>("PendingMotherName")
                        .HasMaxLength(2147483647)
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2147483647)
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("text");

                    b.HasKey("PersonID");

                    b.HasIndex("CityID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FamilyID");

                    b.HasIndex("FatherID");

                    b.HasIndex("MaternalFamilyID");

                    b.HasIndex("MotherID");

                    b.HasIndex("PaternalFamilyID");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.Photo", b =>
                {
                    b.Property<int>("PhotoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PhotoID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PhotoID"));

                    b.Property<int>("AlbumID")
                        .HasColumnType("integer")
                        .HasColumnName("AlbumID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DateTaken")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateTaken");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("FileSize");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("Height");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Location");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("ThumbnailUrl");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Title");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("integer")
                        .HasColumnName("UploadedBy");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Url");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("Width");

                    b.HasKey("PhotoID");

                    b.HasIndex("AlbumID");

                    b.HasIndex("UploadedBy");

                    b.ToTable("Photo");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.PhotoLike", b =>
                {
                    b.Property<int>("LikeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("LikeID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LikeID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("PhotoID")
                        .HasColumnType("integer")
                        .HasColumnName("PhotoID");

                    b.Property<int>("UserID")
                        .HasColumnType("integer")
                        .HasColumnName("UserID");

                    b.HasKey("LikeID");

                    b.HasIndex("PhotoID");

                    b.HasIndex("UserID");

                    b.ToTable("PhotoLike");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.PhotoPerson", b =>
                {
                    b.Property<int>("PhotoPersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PhotoPersonID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PhotoPersonID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("PersonID")
                        .HasColumnType("integer")
                        .HasColumnName("PersonID");

                    b.Property<int>("PhotoID")
                        .HasColumnType("integer")
                        .HasColumnName("PhotoID");

                    b.Property<decimal?>("PositionX")
                        .HasColumnType("numeric")
                        .HasColumnName("PositionX");

                    b.Property<decimal?>("PositionY")
                        .HasColumnType("numeric")
                        .HasColumnName("PositionY");

                    b.Property<int?>("TaggedBy")
                        .HasColumnType("integer")
                        .HasColumnName("TaggedBy");

                    b.HasKey("PhotoPersonID");

                    b.HasIndex("PersonID");

                    b.HasIndex("PhotoID");

                    b.HasIndex("TaggedBy");

                    b.ToTable("PhotoPerson");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.Poll", b =>
                {
                    b.Property<int>("PollID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pollid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PollID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer")
                        .HasColumnName("creatorid");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DescriptionVisibility")
                        .HasColumnType("text")
                        .HasColumnName("description_visibility");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enddate");

                    b.Property<int>("FamilyID")
                        .HasColumnType("integer")
                        .HasColumnName("familyid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("PollType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("polltype");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startdate");

                    b.Property<string>("TargetAudience")
                        .HasColumnType("jsonb")
                        .HasColumnName("target_audience");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("VisibilityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("visibility_type");

                    b.HasKey("PollID");

                    b.ToTable("polls");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.PollOption", b =>
                {
                    b.Property<int>("OptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("optionid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OptionID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<int>("OptionOrder")
                        .HasColumnType("integer")
                        .HasColumnName("optionorder");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("optiontext");

                    b.Property<int>("PollID")
                        .HasColumnType("integer")
                        .HasColumnName("pollid");

                    b.HasKey("OptionID");

                    b.HasIndex("PollID");

                    b.ToTable("polloptions");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.PollParticipant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("participant_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ParticipantId"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("personid");

                    b.Property<int>("PollId")
                        .HasColumnType("integer")
                        .HasColumnName("pollid");

                    b.HasKey("ParticipantId");

                    b.HasIndex("PollId");

                    b.ToTable("poll_participants");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.PollVote", b =>
                {
                    b.Property<int>("VoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("voteid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VoteID"));

                    b.Property<int>("OptionID")
                        .HasColumnType("integer")
                        .HasColumnName("optionid");

                    b.Property<int>("PollID")
                        .HasColumnType("integer")
                        .HasColumnName("pollid");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("votedat");

                    b.Property<int>("VoterID")
                        .HasColumnType("integer")
                        .HasColumnName("voterid");

                    b.HasKey("VoteID");

                    b.HasIndex("OptionID");

                    b.HasIndex("PollID");

                    b.ToTable("pollvotes");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.Wedding", b =>
                {
                    b.Property<int>("WeddingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WeddingID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime?>("DivorceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ManID")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("PatrilinealFamilyID")
                        .HasColumnType("integer")
                        .HasColumnName("PatrilinealFamilyID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<DateTime>("WeddingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WomanID")
                        .HasColumnType("integer");

                    b.HasKey("WeddingID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ManID");

                    b.HasIndex("PatrilinealFamilyID");

                    b.HasIndex("WomanID");

                    b.ToTable("Wedding");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.Album", b =>
                {
                    b.HasOne("FamilyTreeAPI.Models.Connexion", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTreeAPI.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventID");

                    b.HasOne("FamilyTreeAPI.Models.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Event");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.AlbumComment", b =>
                {
                    b.HasOne("FamilyTreeAPI.Models.Album", "Album")
                        .WithMany("Comments")
                        .HasForeignKey("AlbumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTreeAPI.Models.Connexion", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.AlbumPermission", b =>
                {
                    b.HasOne("FamilyTreeAPI.Models.Album", "Album")
                        .WithMany("Permissions")
                        .HasForeignKey("AlbumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTreeAPI.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonID");

                    b.HasOne("FamilyTreeAPI.Models.Connexion", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("Album");

                    b.Navigation("Person");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.Connexion", b =>
                {
                    b.HasOne("FamilyTreeAPI.Models.Family", null)
                        .WithMany("Connexions")
                        .HasForeignKey("FamilyID");

                    b.HasOne("FamilyTreeAPI.Models.Person", "Person")
                        .WithOne("Connexion")
                        .HasForeignKey("FamilyTreeAPI.Models.Connexion", "IDPerson");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.Event", b =>
                {
                    b.HasOne("FamilyTreeAPI.Models.Connexion", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("FamilyTreeAPI.Models.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.EventParticipant", b =>
                {
                    b.HasOne("FamilyTreeAPI.Models.Event", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTreeAPI.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.EventPhoto", b =>
                {
                    b.HasOne("FamilyTreeAPI.Models.Event", "Event")
                        .WithMany("Photos")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTreeAPI.Models.Connexion", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploadedBy");

                    b.Navigation("Event");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.Family", b =>
                {
                    b.HasOne("FamilyTreeAPI.Models.Person", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.FamilyRelation", b =>
                {
                    b.HasOne("FamilyTreeAPI.Models.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTreeAPI.Models.Person", "Person")
                        .WithMany("FamilyRelations")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.MarriageUnion", b =>
                {
                    b.HasOne("FamilyTreeAPI.Models.Wedding", "Wedding")
                        .WithMany("Unions")
                        .HasForeignKey("WeddingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wedding");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.Person", b =>
                {
                    b.HasOne("FamilyTreeAPI.Models.City", "City")
                        .WithMany("Persons")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTreeAPI.Models.Connexion", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("FamilyTreeAPI.Models.Family", "Family")
                        .WithMany("Members")
                        .HasForeignKey("FamilyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyTreeAPI.Models.Person", "Father")
                        .WithMany("ChildrenAsFather")
                        .HasForeignKey("FatherID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyTreeAPI.Models.Family", "MaternalFamily")
                        .WithMany()
                        .HasForeignKey("MaternalFamilyID");

                    b.HasOne("FamilyTreeAPI.Models.Person", "Mother")
                        .WithMany("ChildrenAsMother")
                        .HasForeignKey("MotherID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyTreeAPI.Models.Family", "PaternalFamily")
                        .WithMany()
                        .HasForeignKey("PaternalFamilyID");

                    b.Navigation("City");

                    b.Navigation("Creator");

                    b.Navigation("Family");

                    b.Navigation("Father");

                    b.Navigation("MaternalFamily");

                    b.Navigation("Mother");

                    b.Navigation("PaternalFamily");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.Photo", b =>
                {
                    b.HasOne("FamilyTreeAPI.Models.Album", "Album")
                        .WithMany("Photos")
                        .HasForeignKey("AlbumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTreeAPI.Models.Connexion", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.PhotoLike", b =>
                {
                    b.HasOne("FamilyTreeAPI.Models.Photo", "Photo")
                        .WithMany("Likes")
                        .HasForeignKey("PhotoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTreeAPI.Models.Connexion", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.PhotoPerson", b =>
                {
                    b.HasOne("FamilyTreeAPI.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTreeAPI.Models.Photo", "Photo")
                        .WithMany("TaggedPersons")
                        .HasForeignKey("PhotoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTreeAPI.Models.Connexion", "Tagger")
                        .WithMany()
                        .HasForeignKey("TaggedBy");

                    b.Navigation("Person");

                    b.Navigation("Photo");

                    b.Navigation("Tagger");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.PollOption", b =>
                {
                    b.HasOne("FamilyTreeAPI.Models.Poll", "Poll")
                        .WithMany("Options")
                        .HasForeignKey("PollID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.PollParticipant", b =>
                {
                    b.HasOne("FamilyTreeAPI.Models.Poll", "Poll")
                        .WithMany()
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.PollVote", b =>
                {
                    b.HasOne("FamilyTreeAPI.Models.PollOption", "Option")
                        .WithMany()
                        .HasForeignKey("OptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTreeAPI.Models.Poll", "Poll")
                        .WithMany()
                        .HasForeignKey("PollID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Option");

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.Wedding", b =>
                {
                    b.HasOne("FamilyTreeAPI.Models.Connexion", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("FamilyTreeAPI.Models.Person", "Man")
                        .WithMany("WeddingsAsMan")
                        .HasForeignKey("ManID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyTreeAPI.Models.Family", "PatrilinealFamily")
                        .WithMany()
                        .HasForeignKey("PatrilinealFamilyID");

                    b.HasOne("FamilyTreeAPI.Models.Person", "Woman")
                        .WithMany("WeddingsAsWoman")
                        .HasForeignKey("WomanID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Man");

                    b.Navigation("PatrilinealFamily");

                    b.Navigation("Woman");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.Album", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Permissions");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.City", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.Event", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.Family", b =>
                {
                    b.Navigation("Connexions");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.Person", b =>
                {
                    b.Navigation("ChildrenAsFather");

                    b.Navigation("ChildrenAsMother");

                    b.Navigation("Connexion");

                    b.Navigation("FamilyRelations");

                    b.Navigation("WeddingsAsMan");

                    b.Navigation("WeddingsAsWoman");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.Photo", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("TaggedPersons");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.Poll", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("FamilyTreeAPI.Models.Wedding", b =>
                {
                    b.Navigation("Unions");
                });
#pragma warning restore 612, 618
        }
    }
}
